# Generated by Django 4.2 on 2023-06-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_cliente_alter_ticket_evento'),
        ('escaneoQR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escaneoqr',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaneo_qr', to='ticket.ticket'),
        ),
    ]
