# Generated by Django 4.2 on 2023-06-24 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(default=datetime.datetime.now)),
                ('ubicacion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_ticket', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
