# Generated by Django 4.2 on 2023-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_ticket',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
