# Generated by Django 4.2 on 2023-06-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_cliente'),
        ('custom_user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tickets',
            field=models.ManyToManyField(related_name='usuarios', to='ticket.ticket'),
        ),
    ]
